# Makefile for the GCC curses/termcap library (16 bit int default)

CC= d:\gnu\bin\gcc.ttp
CPP=d:\gnu\bin\gcc-cpp.ttp
AR= d:\gnu\bin\gcc-ar.ttp
AS= $(CC)
LIB = d:\gnu\lib
INC = d:\gnu\include

MODEL = -I. -mshort
DEFINES = -DDGK -DGEMDOS
COPTS= -O -fomit-frame-pointer -fstrength-reduce \
 -DNDEBUG $(DEFINES) $(XFLAGS)

# normal CFLAGS
CFLAGS= $(MODEL) $(COPTS)

# CFLAGS sans -fomit-frame-pointer
CFFLAGS = $(MODEL) -O -DNDEBUG $(DEFINES) $(XFLAGS)

# cflags for stuff that needs to be compiled with 32 bit ints
CLFLAGS= $(COPTS) -DSHORTLIB $(XFLAGS)

# flags to $(CC) when it runs the assembler only
ASFLAGS= -c

# pre-processor flags
PPFLAGS= -P -D__MSHORT__ -DNDEBUG

# library targets
CURSES= curses16.olb
TERMCAP = termcap16.olb

# the stuff to make
ALL= $(CURSES) $(TERMCAP)

TESTS = testtcp.ttp twinkle.ttp worms.ttp

include mincl
